version: '2'

services:
  mdb:
    image: mongo:3.4.10
    ports:
      - "27017:27017"
    command: mongod --replSet=bigchain-rs

  bdb:
    build:
      context: .
      dockerfile:  ./Dockerfile
    volumes:
      - ./bigchaindb/bigchaindb:/usr/src/app/bigchaindb
      - ./bigchaindb/tests:/usr/src/app/tests
      - ./bigchaindb/docs:/usr/src/app/docs
      - ./bigchaindb/setup.py:/usr/src/app/setup.py
      - ./bigchaindb/setup.cfg:/usr/src/app/setup.cfg
      - ./bigchaindb/pytest.ini:/usr/src/app/pytest.ini
      - ./bigchaindb/tox.ini:/usr/src/app/tox.ini
      - ./bigchaindb/Makefile:/usr/src/app/Makefile
    environment:
      BIGCHAINDB_DATABASE_BACKEND: mongodb
      BIGCHAINDB_DATABASE_HOST: mdb
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_KEYPAIR_PUBLIC: GW1nrdZm4mbVC8ePeiGWz6DqHexqewqy5teURVHi3RG4
      BIGCHAINDB_KEYPAIR_PRIVATE: 2kQgBtQnHoauw8QchKM7xYvEBW1QDoHzhBsCL9Vi1AzB
      BIGCHAINDB_CONSENSUS_PLUGIN: consensus_smart_assets
      BIGCHAINDB_WSSERVER_PORT: 9985
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_DATABASE_NAME: bigchain
      BIGCHAINDB_DATABASE_REPLICASET: bigchain-rs
      BIGCHAINDB_WSSERVER_SCHEME: ws
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
    ports:
      - "9984:9984"
      - "9985:9985"
    command: bigchaindb start
